version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: docker/backend/dockerFile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/dockerFile
    ports:
      - "4200:80"
    depends_on:
      - backend