version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: portfolio/dockerFile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: portfolio-front/dockerFile
    ports:
      - "4200:80"
    depends_on:
      - backend