FROM node:20 AS build

WORKDIR /app

COPY portfolio-front/package*.json ./
RUN npm install

COPY portfolio-front/ .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist/portfolio-front/browser /usr/share/nginx/html
COPY portfolio-front/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80