spring.application.name=portfolio

# Database configuration
# Database configuration
spring.datasource.url=jdbc:postgresql://dpg-d7huq7u7r5hc73c24bkg-a.oregon-postgres.render.com:5432/portfolio_alicia_db
spring.datasource.username=portfolio_alicia_db_user
spring.datasource.password=VAh1merRpTDfFSmaGGE0lPCfQDRLbuOp
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# puerto
server.port=${PORT:8080}
